export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/user";
export * from "@/pages/dashboard/employee/viewuser";
export * from "@/pages/dashboard/employee/adduser";  
export * from "@/pages/dashboard/employee/edituser";
export * from "@/pages/dashboard/task-management/createusertask"
export * from "@/pages/dashboard/task-management/viewusertask"
export * from "@/pages/dashboard/department/adddept";
export * from "@/pages/dashboard/department/managedept";
export * from "@/pages/dashboard/department/editdept";
