export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/user";
export * from "@/pages/dashboard/employee/manage-employee";
export * from "@/pages/dashboard/employee/add-employee";  
export * from "@/pages/dashboard/employee/edit-employee";
export * from "@/pages/dashboard/task-management/createusertask"
export * from "@/pages/dashboard/task-management/viewusertask"
export * from "@/pages/dashboard/department/add-deptartment";
export * from "@/pages/dashboard/department/manage-deptartment";
export * from "@/pages/dashboard/department/edit-deptartment";
export * from "@/pages/dashboard/projects/add-project";
export * from "@/pages/dashboard/projects/manage-projects";  
export * from "@/pages/dashboard/projects/edit-project";
